package com.tpfinal.vistas;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import com.tpfinal.modelo.Fecha;
import com.tpfinal.modelo.Venta;

public class AltaVenta extends javax.swing.JFrame {

    Connection con;
    PreparedStatement s;
    ResultSet r;
    ResultSetMetaData rsm;
    DefaultTableModel dtm;
    int total;

    Fecha a = new Fecha();

    public AltaVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_TablaDetalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTB_TablaDetalle3 = new javax.swing.JTable();
        JLB_TotalaPagar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextFieldcliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cancelar2 = new javax.swing.JButton();

        JTB_TablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUC", "NOMBRE", "CANTIDAD", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(JTB_TablaDetalle);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo del Producto:");

        jLabel2.setText("Cantidad:");

        jTextField2.setText("1");

        jButton3.setText("Añadir al Carrito");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Calcular Total");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sistema de Ventas");

        JTB_TablaDetalle3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUC", "NOMBRE", "PRECIO", "Stock del Producto"
            }
        ));
        jScrollPane2.setViewportView(JTB_TablaDetalle3);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Concretar Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("DNI del Cliente:");

        Cancelar2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Cancelar2.setText("Cancelar Venta");
        Cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextFieldcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Cancelar2)
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLB_TotalaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(Cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton4)
                            .addComponent(JLB_TotalaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int cantidad = 0;
        String x = jTextField2.getText();
        int xx = Integer.parseInt(x);

        while (cantidad < xx) {
            cantidad = cantidad + 1;
            try {

                String url = "jdbc:sqlserver://Agustin-PC:1433;databaseName=Kiosco";

                String user = "usuario_java";
                String clave = "123";

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection(url, user, clave);

                s = con.prepareStatement("select id_producto, Nombre, Precio, Stock from Producto WHERE id_producto = " + jTextField1.getText() + "");
                r = s.executeQuery();
                rsm = r.getMetaData();
                ArrayList<Object[]> data = new ArrayList<>();
                while (r.next()) {
                    total = total + Integer.parseInt(r.getString(3)); //aca
                    Object[] rows = new Object[rsm.getColumnCount()];
                    for (int i = 0; i < rows.length; i++) {
                        rows[i] = r.getObject(i + 1);
                    }
                    data.add(rows);
                }
                dtm = (DefaultTableModel) this.JTB_TablaDetalle3.getModel();
                for (int i = 0; i < data.size(); i++) {
                    dtm.addRow(data.get(i));
                }
            } catch (ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String totall = Integer.toString(total);
        JLB_TotalaPagar.setText(totall);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String elid = null;
        /// Seleccina el id   
        try {

            String url = "jdbc:sqlserver://Agustin-PC:1433;databaseName=Kiosco";

            String user = "usuario_java";
            String clave = "123";

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(url, user, clave);

            s = con.prepareStatement("select id from id");
            r = s.executeQuery();
            rsm = r.getMetaData();
            ArrayList<Object[]> data = new ArrayList<>();
            while (r.next()) {
                elid = (r.getString(1));

                Object[] rows = new Object[rsm.getColumnCount()];
                for (int i = 0; i < rows.length; i++) {
                    rows[i] = r.getObject(i + 1);
                }
                data.add(rows);
            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

        Connection con = null;
        PreparedStatement s;

        String url = "jdbc:sqlserver://Agustin-PC:1433;databaseName=Kiosco";
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String user = "usuario_java";
        String clave = "123";

        for (int i = 0; i < JTB_TablaDetalle3.getRowCount(); i++) {

            String elstock = "";
            int elstock2 = 0;

            String codpro = JTB_TablaDetalle3.getValueAt(i, 0).toString();
            String prod = JTB_TablaDetalle3.getValueAt(i, 1).toString();
            String cant = JTB_TablaDetalle3.getValueAt(i, 2).toString();
            String car = jTextFieldcliente.getText();

            try {

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection(url, user, clave);

                s = con.prepareStatement("select Stock from Producto WHERE id_producto = " + codpro + "");
                r = s.executeQuery();
                rsm = r.getMetaData();
                ArrayList<Object[]> data = new ArrayList<>();
                while (r.next()) {

                    Object[] rows = new Object[rsm.getColumnCount()];
                    for (int m = 0; m < rows.length; m++) {
                        rows[m] = r.getObject(m + 1);
                        elstock = (r.getString(1));
                        elstock2 = Integer.parseInt(elstock);
                    }
                    data.add(rows);

                }
            } catch (ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }

            if (elstock2 >= 1) {
                {

                    try {
                        Class.forName(driver);
                        con = DriverManager.getConnection(url, user, clave);
                        s = con.prepareStatement("UPDATE Producto SET Stock=(?) Where id_producto = " + codpro + "");
                        elstock2 = elstock2 - 1;
                        elstock = Integer.toString(elstock2);
                        s.setString(1, elstock);

                        s.executeUpdate();

                    } catch (ClassNotFoundException e) {
                        JOptionPane.showMessageDialog(null, e);
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                    Venta v = new Venta();
                    v.Venta(codpro, prod, cant, car, elid);

                }
            }

/// refresca el id
        }

        try {
            Class.forName(driver);
            con = DriverManager.getConnection(url, user, clave);
            s = con.prepareStatement("UPDATE id SET id =(?)");

            int elidn;
            elidn = Integer.parseInt(elid);
            elidn = elidn + 1;
            elid = Integer.toString(elidn);
            s.setString(1, elid);

            s.executeUpdate();

            JOptionPane.showMessageDialog(null, "Venta Almacenada ");

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void Cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar2ActionPerformed
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_Cancelar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaVenta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar2;
    private javax.swing.JTextField JLB_TotalaPagar;
    public static javax.swing.JTable JTB_TablaDetalle;
    public static javax.swing.JTable JTB_TablaDetalle3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldcliente;
    // End of variables declaration//GEN-END:variables
}
